### ISSUE TITLE
Unable to run app on OS X El Capitan

### ISSUE THREAD

**Issue by xicombd** [ipfs/station#121]
Hey there!

I'm having trouble running the app on OS X El Capitan. The tray icon appears for 2 seconds but it crashes right after. 

Below is the result log of doing `npm start`:
```
➜  station git:(master) npm start

> ipfs-station@1.0.0-alpha.1 start /Users/xicombd/Code/ipfs/station
> npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"


> ipfs-station@1.0.0-alpha.1 clean /Users/xicombd/Code/ipfs/station
> rimraf build && mkdir build


> ipfs-station@1.0.0-alpha.1 build:babel /Users/xicombd/Code/ipfs/station
> babel app/config.js -o build/config.js && ./node_modules/.bin/babel app/controls -d build/controls && ./node_modules/.bin/babel app/init.js -o build/init.js && ./node_modules/.bin/babel app/helpers.js -o build/helpers.js

app/controls/drag-drop.js -> build/controls/drag-drop.js
app/controls/open-browser.js -> build/controls/open-browser.js
app/controls/open-console.js -> build/controls/open-console.js
app/controls/open-settings.js -> build/controls/open-settings.js
app/controls/utils.js -> build/controls/utils.js
[0] Development server started at http://localhost:3000
[1]
[1] > ipfs-station@1.0.0-alpha.1 electron /Users/xicombd/Code/ipfs/station
[1] > electron index.js
[1]
[1] info: Booting
[1] info: Application is ready
[1] info: Starting tray
[1] Uncaught SyntaxError: Unexpected token u
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1]     at <error: TypeError: Cannot read property 'name' of undefined>
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at Request.object.(anonymous function) [as on] (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at Request.init (/Users/xicombd/Code/ipfs/station/node_modules/request/request.js:201:10)
[1]     at new Request (/Users/xicombd/Code/ipfs/station/node_modules/request/request.js:140:8)
[1]     at request (/Users/xicombd/Code/ipfs/station/node_modules/request/index.js:55:10)
[1]     at makeRequest (/Users/xicombd/Code/ipfs/station/node_modules/ipfs-api/src/request-api.js:80:10)
[1]     at requestAPI (/Users/xicombd/Code/ipfs/station/node_modules/ipfs-api/src/request-api.js:129:5)
[1]     at Object.get (/Users/xicombd/Code/ipfs/station/node_modules/ipfs-api/src/index.js:52:14)
[1]     at _lookup (/Users/xicombd/Code/ipfs/station/node_modules/ipfs-geoip/lib/lookup.js:13:15)
[1]     at conf.original (/Users/xicombd/Code/ipfs/station/node_modules/memoizee/ext/async.js:103:18)
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at Request.object.(anonymous function) [as on] (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at Request.init (/Users/xicombd/Code/ipfs/station/node_modules/request/request.js:201:10)
[1]     at new Request (/Users/xicombd/Code/ipfs/station/node_modules/request/request.js:140:8)
[1]     at request (/Users/xicombd/Code/ipfs/station/node_modules/request/index.js:55:10)
[1]     at makeRequest (/Users/xicombd/Code/ipfs/station/node_modules/ipfs-api/src/request-api.js:80:10)
[1]     at requestAPI (/Users/xicombd/Code/ipfs/station/node_modules/ipfs-api/src/request-api.js:129:5)
[1]     at IpfsAPI.self.id (/Users/xicombd/Code/ipfs/station/node_modules/ipfs-api/src/index.js:159:12)
[1]     at pollStats (/Users/xicombd/Code/ipfs/station/build/init.js:62:8)
[1]     at /Users/xicombd/Code/ipfs/station/build/init.js:103:5
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at Stream.object.(anonymous function) [as on] (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at /Users/xicombd/Code/ipfs/station/node_modules/ipfsd-ctl/index.js:107:12
[1]     at parseConfig (/Users/xicombd/Code/ipfs/station/node_modules/ipfsd-ctl/index.js:178:5)
[1]     at Object.startDaemon (/Users/xicombd/Code/ipfs/station/node_modules/ipfsd-ctl/index.js:93:7)
[1]     at onStartDaemon (/Users/xicombd/Code/ipfs/station/build/init.js:92:8)
[1]     at EventEmitter.<anonymous> (/Users/xicombd/Code/ipfs/station/build/init.js:263:9)
[1]     at EventEmitter.<anonymous> (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
[1]     at emitNone (events.js:67:13)
[1]     at EventEmitter.emit (events.js:166:7)
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at EventEmitter.object.(anonymous function) [as on] (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at /Users/xicombd/Code/ipfs/station/build/init.js:241:8
[1]     at Object.module.exports.local (/Users/xicombd/Code/ipfs/station/node_modules/ipfsd-ctl/index.js:199:5)
[1]     at Object.boot (/Users/xicombd/Code/ipfs/station/build/init.js:236:25)
[1]     at EventEmitter.<anonymous> (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
[1]     at emitOne (events.js:77:13)
[1]     at EventEmitter.emit (events.js:169:7)
[1]     at Server.handleListening (/Users/xicombd/Code/ipfs/station/node_modules/monogamous/dist/monogamous.js:65:23)
[1]     at Server.<anonymous> (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
[1] ----------------------------------------
[1]     at EventEmitter.on
[1]     at makeWrappedCallback (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
[1]     at EventEmitter.object.(anonymous function) [as on] (/Users/xicombd/Code/ipfs/station/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
[1]     at Object.<anonymous> (/Users/xicombd/Code/ipfs/station/index.js:30:8)
[1]     at Module._compile (module.js:434:26)
[1]     at Object.Module._extensions..js (module.js:452:10)
[1]     at Module.load (module.js:355:32)
[1]     at Function.Module._load (module.js:310:12)
[1]     at Object.<anonymous> (/Users/xicombd/Code/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:246:23)
[1]     at Module._compile (module.js:434:26)
[1]     at Object.Module._extensions..js (module.js:452:10)
[1] Uncaught undefined
[1] Uncaught undefined
[1] Uncaught undefined
[1] error: Uncaught Exception:   undefined 0=
[1] info: Shutting down application
[1] info: Stopping daemon
[1] info: Stopped daemon
[1] info: Stopped daemon
[1]
[1] npm ERR! Darwin 15.0.0
[1] npm ERR! argv "/Users/xicombd/.nvm/versions/node/v4.2.2/bin/node" "/Users/xicombd/.nvm/versions/node/v4.2.2/bin/npm" "run" "electron"
[1] npm ERR! node v4.2.2
[1] npm ERR! npm  v3.3.12
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! ipfs-station@1.0.0-alpha.1 electron: `electron index.js`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the ipfs-station@1.0.0-alpha.1 electron script 'electron index.js'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the ipfs-station package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     electron index.js
[1] npm ERR! You can get their info via:
[1] npm ERR!     npm owner ls ipfs-station
[1] npm ERR! There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /Users/xicombd/Code/ipfs/station/npm-debug.log
[1] npm run electron exited with code 1
--> Sending SIGTERM to other processes..
[0] node dev-server.js exited with code null

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/xicombd/.nvm/versions/node/v4.2.2/bin/node" "/Users/xicombd/.nvm/versions/node/v4.2.2/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! ipfs-station@1.0.0-alpha.1 start: `npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipfs-station@1.0.0-alpha.1 start script 'npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipfs-station package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build:babel && ./node_modules/.bin/concurrent --kill-others "node dev-server.js" "npm run electron"
npm ERR! You can get their info via:
npm ERR!     npm owner ls ipfs-station
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xicombd/Code/ipfs/station/npm-debug.log
```

My node and npm versions are:
 - node: `v4.2.2`
 - npm: `v3.3.12`

I tried removing `node_modules` and npm install a few times and the result has been always the same.

Am I missing something?

Thanks!

**Comment by Dignifiedquire** [comment]
Thanks for the report, what exact version have you tried running? (git sha) It looks like this is the same error as in #106

**Comment by xicombd** [comment]
Yeah, my mistake, I noticed this a few days ago and forgot to git pull today somehow.

It's fixed now, sorry for bothering!

**Comment by Dignifiedquire** [comment]
Great thanks for the feedback and enjoy :)
