### ISSUE TITLE
Problem running on Mac OSX 10.9.4 Mavericks

### ISSUE THREAD

**Issue by swang** [ipfs/station#135]
Node -> 4
npm -> 2.14.2
I copy the instructions in the README, but when I exec `npm run start` I get:

```
> ipfs-station@1.0.0-alpha.1 prestart /Users/shuan/Projects/ipfs/station
> npm run clean && npm run build:babel

> ipfs-station@1.0.0-alpha.1 clean /Users/shuan/Projects/ipfs/station
> rimraf build && mkdir build

> ipfs-station@1.0.0-alpha.1 build:babel /Users/shuan/Projects/ipfs/station
> babel app/config.js -o build/config.js && babel app/controls -d build/controls && babel app/init.js -o build/init.js

app/controls/drag-drop.js -> build/controls/drag-drop.js
app/controls/open-browser.js -> build/controls/open-browser.js
app/controls/open-console.js -> build/controls/open-console.js
app/controls/open-settings.js -> build/controls/open-settings.js
app/controls/utils.js -> build/controls/utils.js

> ipfs-station@1.0.0-alpha.1 start /Users/shuan/Projects/ipfs/station
> concurrent --kill-others 'node dev-server.js' 'npm run electron'

[0] Development server started at http://localhost:3000
[1] 
[1] > ipfs-station@1.0.0-alpha.1 electron /Users/shuan/Projects/ipfs/station
[1] > electron index.js
[1] 
[1] (electron) app.getDataPath is deprecated. Use app.getPath instead.
[1] info: Booting
[1] (electron) loadUrl is deprecated. Use loadURL instead.
[1] info: Application is ready
[1] info: Starting tray
[0] webpack built d358ff66ae09b55454ef in 3826ms
[1] error: Uncaught Exception: Cannot read property 'Hash' of undefined [TypeError: Cannot read property 'Hash' of undefined] TypeError: Cannot read property 'Hash' of undefined
[1]     at /Users/shuan/Projects/ipfs/station/node_modules/ipfs-geoip/lib/lookup.js:27:58
[1]     at finish (/Users/shuan/Projects/ipfs/station/node_modules/ipfs-api/node_modules/wreck/lib/index.js:319:16)
[1]     at wrapped (/Users/shuan/Projects/ipfs/station/node_modules/ipfs-api/node_modules/wreck/node_modules/hoek/lib/index.js:867:20)
[1]     at onReaderFinish (/Users/shuan/Projects/ipfs/station/node_modules/ipfs-api/node_modules/wreck/lib/index.js:365:16)
[1]     at g (events.js:260:16)
[1]     at emitNone (events.js:72:20)
[1]     at emit (events.js:166:7)
[1]     at finishMaybe (_stream_writable.js:468:14)
[1]     at endWritable (_stream_writable.js:478:3)
[1]     at Writable.end (_stream_writable.js:443:5) { '0': [TypeError: Cannot read property 'Hash' of undefined] }
[1] info: Shutting down application
[1] info: Stopping daemon
[1] info: Stopped daemon
[1] info: Stopped daemon
[1] 
[1] npm
[1]  
[1] ERR!
[1]  Darwin 13.3.0
[1] npm
[1]  
[1] ERR! argv
[1]  "/Users/shuan/.nvm/versions/node/v4.0.0/bin/node" "/Users/shuan/.nvm/versions/node/v4.0.0/bin/npm" "run" "electron"
[1] npm
[1]  ERR! node
[1]  v4.0.0
[1] npm ERR! 
[1] npm  v2.14.2
[1] npm
[1]  ERR! code ELIFECYCLE
[1] npm ERR!
[1]  ipfs-station@1.0.0-alpha.1 electron: `electron index.js`
[1] npm ERR!
[1]  Exit status 1
[1] npm
[1]  ERR!
[1]  
[1] npm ERR!
[1]  Failed at the ipfs-station@1.0.0-alpha.1 electron script 'electron index.js'.
[1] npm ERR! This is most likely a problem with the ipfs-station package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     electron index.js
[1] npm ERR! You can get their info via:
[1] npm ERR!     npm owner ls ipfs-station
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /Users/shuan/Projects/ipfs/station/npm-debug.log
[1] npm run electron exited with code 1
--> Sending SIGTERM to other processes..
[0] node dev-server.js exited with code null
```
I tried debugging this myself, but it seems like the ip being passed into ipfs-geoip running the lookup function is `::1` which seems to be the ipv6 loopback address. Converting this using `aton4` makes it return 0.

I've tried looking around ipfs for documentation of this problem but couldn't find anything so apologies if this is a known issue. Otherwise I have no clue why its passing `::1` as the ip.

**Comment by Dignifiedquire** [comment]
Thanks, this should be fixed in https://github.com/ipfs/ipfs-geoip/pull/4, will try to get a release out asap to fix this.

**Comment by Dignifiedquire** [comment]
Can you please try out the latest master and let me know if this still happens?

**Comment by swang** [comment]
I can install it now from OSX, but I had to upgrade node to 4.2.2 due to errors with caniuse. It works fine after I do that.
