### ISSUE TITLE
Shutting down using ctrl+c does not cleanup the menubar instance (OS X)

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/station#145]

**Comment by Dignifiedquire** [comment]
Found some more details: https://gist.github.com/Dignifiedquire/f4a47f17109aaea92a70 but no idea what this means

**Comment by Dignifiedquire** [comment]
@diasdavid ping if you could take a look at let me know if you have any ideas

**Comment by diasdavid** [comment]
just tried a new clean install again and still throws for me :(

**Comment by Dignifiedquire** [comment]
Okay the reason is that `ipfsd.local` does not work as expected. When running a daemon on another terminal the error goes away. Needs more investigation

**Comment by Dignifiedquire** [comment]
Found some more details, as to the issues. It seems that the daemon has not finished starting when killing it, and that causes issues and the relevant hanging. After the daemon has launched stopping station poses no issues anymore.

**Comment by diasdavid** [comment]
@Dignifiedquire I would love to help you debug this ctrl+c thing, but first I would need to be able to run the daemon as good as you and so far I still have the problem of it crashing as well as: https://github.com/ipfs/station/issues/106 and https://github.com/ipfs/station/issues/106 . 

I believe it would be a good strategy to fix the packaging of the right IPFS binary with station and create a separate daemon + repo so that we can have reproducible builds and runs before we try to use the local daemons.

**Comment by Dignifiedquire** [comment]
Similar error when pressing stop in the uI

```
[1] info: Application is ready
[1] info: Starting tray
[0] webpack built b2261228e4a052803236 in 11628ms
[1] creating node
[1] info: Stopping daemon
[1] error: Uncaught Exception: context canceled { [Error: context canceled] code: 0 } Error: context canceled
[1]     at /Users/dignifiedquire/opensource/ipfs/station/node_modules/ipfsd-ctl/node_modules/ipfs-api/src/request-api.js:31:21
[1]     at finish (/Users/dignifiedquire/opensource/ipfs/station/node_modules/wreck/lib/index.js:146:20)
[1]     at wrapped (/Users/dignifiedquire/opensource/ipfs/station/node_modules/wreck/node_modules/hoek/lib/index.js:867:20)
[1]     at ClientRequest.onResponse (/Users/dignifiedquire/opensource/ipfs/station/node_modules/wreck/lib/index.js:169:20)
[1]     at ClientRequest.g (events.js:260:16)
[1]     at emitOne (events.js:77:13)
[1]     at ClientRequest.emit (events.js:169:7)
[1]     at HTTPParser.parserOnIncomingClient (_http_client.js:421:21)
[1]     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
[1]     at Socket.socketOnData (_http_client.js:311:20) { '0': {},
[1]   '1':
[1]    { [Function: require]
[1]      resolve: [Function],
[1]      main:
[1]       Module {
[1]         id: '.',
[1]         exports: {},
[1]         parent: [Object],
[1]         filename: '/Users/dignifiedquire/opensource/ipfs/station/index.js',
[1]         loaded: true,
[1]         children: [Object],
[1]         paths: [Object] },
[1]      extensions: { '.js': [Function], '.json': [Function], '.node': [Function] },
[1]      cache:
[1]       { '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/init.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/common/lib/reset-search-paths.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/common/lib/init.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/exports/electron.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/common/api/lib/exports/electron.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/app.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/common/api/lib/deprecate.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/session.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/menu.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/browser-window.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/ipc-main.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/menu-item.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/objects-registry.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/guest-view-manager.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/navigation-controller.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/guest-window-manager.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/chrome-extension.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/desktop-capturer.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/common/api/lib/shell.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/index.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/monogamous/dist/monogamous.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/monogamous/node_modules/minimist/index.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/dist/stampit.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/collection/forEach.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/arrayEach.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/baseEach.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/baseForOwn.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/baseFor.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/createBaseFor.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/toObject.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/lang/isObject.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/object/keys.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/getNative.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/lang/isNative.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/lang/isFunction.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/isObjectLike.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/isArrayLike.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/getLength.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/baseProperty.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/isLength.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/internal/shimKeys.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/station/node_modules/stampit/node_modules/lodash/lang/isArguments.js': [Object],
[1]         '/Users/dignifiedquire/opensource/ipfs/s
[1] info: Shutting down application
[1] info: Stopping daemon
[1] info: Stopped daemon
^C
```

**Comment by Dignifiedquire** [comment]
The errors are coming from `ipfs-geoip` dropping it's usage for now until I can fix it
