### ISSUE TITLE
OSX install issues.

### ISSUE THREAD

**Issue by 14lox** [ipfs/station#425]
OSX: `10.11.6 (15G1004)`
node: `v6.9.1`
npm: `3.10.8`

`$ npm install`
```
npm WARN eslint-config-standard@6.2.1 requires a peer of eslint@>=3.8.1 but none was installed.
npm WARN eslint-config-standard@6.2.1 requires a peer of eslint-plugin-promise@>=3.3.0 but none was installed.
```

`$ npm start`

```
> ipfs-station@1.0.0-alpha.1 start /Users/daicoinbase/station
> electron src/index.js

App threw an error during load
Error: Cannot find module 'babel-runtime/core-js/object/assign'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (../station/node_modules/electron-prebuilt-compile/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (../station/node_modules/electron-prebuilt-compile/node_modules/electron-compile/lib/index.js:3:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by 14lox** [comment]
Hmmm, weird. I tried it again in a different location and now it works. (The very first time I tried to install I had an older version of Node, so that was probably it - it got confused). Closing.
